hash-format = "sha256"

[[files]]
file = "config/experimentalist.json"
hash = "e84e3001112407497f02802b42073aad4ae8d30b480af04671bb9d1d1fbdb182"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "383126b33e651358f3609a4daa02d0914d8fb10fcbd252743ec84b4a3e5280ae"

[[files]]
file = "config/structurify.json"
hash = "548e538211b87ea05ed135a288a8b5e1ab218d98e716bad65c1fa8921ab797b4"

[[files]]
file = "config/yosbr/config/badoptimizations.txt"
hash = "f043b31a1fd029cbcd999a9ba184a1f66b4a8a8f020881c59b870436d8de1103"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "aa798e887fb1fe69563a06e259dc2be59bcb3baf45ec05c1ded759ac6c1ff3ef"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "3817e94107bb1c7358beebb80b1810e822de38be430f855cf14828c38018e8e2"

[[files]]
file = "config/yosbr/config/immediatelyfast.json"
hash = "fe6551b3aa77d3b624acff41ed6bf65b3d6d5c8821b7bda8875ff7b6b75e0c43"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "5b24c9a57bb6092df95d9e8ec3c79574103967cef4db94508b9b172df1e447e5"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "564937e9bb15ddeb6741ce741a35486bc71b2a9a178d176b6107cfcb30747540"

[[files]]
file = "config/yosbr/options.txt"
hash = "720665a797fd8303d3a2f4e528a449b043dbbd6e9b18bed8646ba98da4141c15"

[[files]]
file = "mods/GravesOfInsanity-1.0.2.jar"
hash = "de17032a3fd289855202444449bddc4eeff35f3b8e1e711306389cc86323caca"

[[files]]
file = "mods/allaybottle.pw.toml"
hash = "d1c57735540c0ee844d1162d13c951403b5472bd06c000511a089ca4175d7470"
metafile = true

[[files]]
file = "mods/always-a-bigger-fish.pw.toml"
hash = "7ffa3a7af846370d2820c64a2ee7034a6e2b0fe18be956c48f8d6d0b6f0ef81f"
metafile = true

[[files]]
file = "mods/atlas-core.pw.toml"
hash = "c9acd83d4bcac593186d5ae34a8ea206a6366db0428bc8b19546902c7e30f3a6"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "a2aa577e93491f2231af331570b5c96a384d260d8770bbd8271742567baaf2f7"
metafile = true

[[files]]
file = "mods/badstdout.pw.toml"
hash = "b2f2254fda825a08d1d41a6dcbeada190c772fda4e06ee06c1a8e6a6c7be51f7"
metafile = true

[[files]]
file = "mods/be-a-doll.pw.toml"
hash = "09dd3907da3cb3655589e74f43bbaf38d30739b7d7cbaccb6da4dd84d381defc"
metafile = true

[[files]]
file = "mods/blocky-bass.pw.toml"
hash = "8f98e389e827ded86f0a2f40f2958749f419aa5d803b9906357f4c8c6c0c9335"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "731284bbfcd8900314bac3244877a4dd7688f14b7142af41d7dc5bd6250dd12d"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "6083db761c82eece49adba0b0cee0b37068422e2eb170b7039ebae65972d03e1"
metafile = true

[[files]]
file = "mods/classic-pipes.pw.toml"
hash = "c86e75b4a1a6d5ccd8481e4cacd4085198317ee03eecd39358dcc76c7ae42a64"
metafile = true

[[files]]
file = "mods/clientier-1.0.0+rev.129d5d2.jar"
hash = "4360e5dbbd53f8678751ebee622456a355c5c7aa653ef804e2504d6da026974e"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/coloredslime.pw.toml"
hash = "75ac825528ce942f1247d8395c78265ffecd22ec24b02acef865223f2b5f49af"
metafile = true

[[files]]
file = "mods/combatify.pw.toml"
hash = "1ea8c7a110e8ff2e687a69cbbd6ef2177d92dfce661625dace10dd99e674625a"
metafile = true

[[files]]
file = "mods/compost.pw.toml"
hash = "8aa0924e004967e53c32b39a2f6541b7a5f7e0a43f3905afd86822dacf1f3655"
metafile = true

[[files]]
file = "mods/creepermultidrop-1.5.0+rev.410e89b.jar"
hash = "9cbca82c56dd6e696ed5ad8334c0e1c4a334bcfba1086c16c43235a9ab06ab52"

[[files]]
file = "mods/defaulted.pw.toml"
hash = "6f1a5a4a200475986ea74a0b5aaf12196d59b88e5cd3b9e1964728a87a945da1"
metafile = true

[[files]]
file = "mods/dudewhatsmygepeuwu-1.2.0+rev.410e89b.jar"
hash = "6a4810cbeb06d06582e88a17eb54801de206f03b49843e9829ade705598e6b14"

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "63fe49aaee4880ff28e30aa558084f7322d5ec2bf110022bc5ae89a9be5cf2bf"
metafile = true

[[files]]
file = "mods/enderscape.pw.toml"
hash = "166aa49f9f782f94654f7edffa1ef3d862f8bdfa669c033df05ba529950dd5f4"
metafile = true

[[files]]
file = "mods/energized-power.pw.toml"
hash = "01f2b74b6dc27b3a146564a0f725a3b3a340a5b29ff1e01fcf27aaa30e242372"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9edcc9e1e87b3612876dbccd411c1eadcc245ab4f3c3b8592e75a2c54df52636"
metafile = true

[[files]]
file = "mods/experimentalist.pw.toml"
hash = "b279ac6b78de6452c97ee308a7de5dd0b94820f7406b9b712d1bfff69e7c1a1b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "b51659a7fdd17e134028a747bd8e4e8fb9ab9d88038577d088049a5c381f09dc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/flying-frisbees.pw.toml"
hash = "d591b3e2be1d8931ca101e98ead53a302ee2e0f6fb4f02967f493ba6ad2d43f6"
metafile = true

[[files]]
file = "mods/frostiful.pw.toml"
hash = "ca7638d78c739aa99229288ab768ec80e39ec3ef051fba3dac0d53d7a1002598"
metafile = true

[[files]]
file = "mods/frozenlib.pw.toml"
hash = "0721e4971dac5b127e56ea4755d5cca0410ed63e60999342ab570cd06ce295dd"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "dc14a906254d528b5ce82c0617c7e15d1ebbd17e4dcc2e852719fad60e8aa2b5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "4516dec6f637aa5b815ebedc125f3f03ca2aca704459560de996a69ad7360ad9"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/inferno.pw.toml"
hash = "2d2dc3770fd58c58e667d2fcb9c4112440858124491d5e4e29f5a1c035e6e129"
metafile = true

[[files]]
file = "mods/its-as-shrimple-as-that.pw.toml"
hash = "7b39243e3d9046c58ebf84353db29ea0b5eb9a58fed0a4688962b9ca1a27133a"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed9d0d5d4078c137900006321d35515cee46058b92df1128ea37cda3e5e1bb2b"
metafile = true

[[files]]
file = "mods/mariposa.pw.toml"
hash = "6fa1104cdb2f103298c032bc7d07964d81dc83f4a802a3dd5ce1cfbc7d2b928c"
metafile = true

[[files]]
file = "mods/mes-moogs-end-structures.pw.toml"
hash = "ebf50a53d72fc55168e01276496dac4db8e062dfc7c0ccee26e9a4857d2ca704"
metafile = true

[[files]]
file = "mods/micro-fighters.pw.toml"
hash = "66e39f75049a09e3169599f24b438cd13fa649a9f39e0e7deede72118e4c2a9a"
metafile = true

[[files]]
file = "mods/misctweaks.pw.toml"
hash = "243a3b8324f9d820a21ae8e3e4609d50896dcd5118e8879725a224f7a0875c4d"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/moogs-structure-lib.pw.toml"
hash = "51ee0d134fdfd195424ff2f3ee80385292684b3b0eb0a05aa5151fe327bfb2d1"
metafile = true

[[files]]
file = "mods/moogs-voyager-structures.pw.toml"
hash = "c0a9864f48bdf589c9bbdca931304ba2e59331913dd25470bb86840c31dc119f"
metafile = true

[[files]]
file = "mods/more_than_a_foxbox.pw.toml"
hash = "bc38b98ba3de7d304efccd77c5338b74b78c337c3af712b613e6e35482725381"
metafile = true

[[files]]
file = "mods/nicespice-1.0.0+rev.410e89b.jar"
hash = "768d97b0010c91e23aad44bfb25532eba5c4c691dd699575fd1ce7f73f76a9b0"

[[files]]
file = "mods/phantom-tweaks.pw.toml"
hash = "2cd4dc490c86105cffd019569eea511a8428e68c93a09c15655f86b94363708a"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
hash = "ab077e767cf4974b5225967f690be78e994b8cc6c7ce6411060f303e7173fd19"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/polyfactory.pw.toml"
hash = "aa8a3ba5b28f9d097fa9992825da1a69b919faf6ea0cfca62caea8f7ee7a7556"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "22a83a04b4df87ab4bbea18228c3cc695551610c66cc79ccc315d783d3f7848f"
metafile = true

[[files]]
file = "mods/rainbethunder-1.3.0+rev.410e89b.jar"
hash = "22b8bd2b5c41e41236413c39dc2ecd1e79c74555a457ed40dbbc9a1e75fd5f3c"

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "2ac27f4c518e7f37ff8c57edd2ed1304d2ae4497641cd1efddc52c9f641ce475"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/scorchful.pw.toml"
hash = "775a48368d72a2d5fe4bc0371ba16136c54b6a18110e0f616de5f2de2672de30"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "886b70d966a36dca61cbd19c4d3955ed657206ce9b8491aad7894c0a369355cd"
metafile = true

[[files]]
file = "mods/simple-death-improvements.pw.toml"
hash = "1ae79cbab1ca28b49d6aaa9fcf3c1c6ab7c421367d650bdc6a181820417ac263"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "eccf47ca447c4970ae7322612b3beab1138b4b510a365dd7f33373f4d33e03a0"
metafile = true

[[files]]
file = "mods/strawberrylib.pw.toml"
hash = "6dd9ca3f03b9264c869bf39bdfc7e9eaf5e3a9dad0b711dae239899f093d0530"
metafile = true

[[files]]
file = "mods/structure-layout-optimizer.pw.toml"
hash = "f6304454d85aaee0b0c475094cd723585a71db537d1304f22b89fa87c5c9b407"
metafile = true

[[files]]
file = "mods/structurify.pw.toml"
hash = "363e1884257a04f7d096f4234e3891bf4ee1a2e74e149f86e9dfbdb589d1d011"
metafile = true

[[files]]
file = "mods/sunken-spires.pw.toml"
hash = "bb55a451673c82a1298a2c2394179ac0c8b75fea012117ba942e3bef72c8fcd6"
metafile = true

[[files]]
file = "mods/superb-steeds.pw.toml"
hash = "d19a3df2b4f7e4e6b51d50e365263e81fbf134b111352ae9c0a9f8f16984c0fd"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "73b96f5d0345bff977a9c69524bedf4805c7070bfa0ba65329dd166b891e64bb"
metafile = true

[[files]]
file = "mods/thermoo.pw.toml"
hash = "d71b93f6c05bf79bad208dd1b5f044b8ce37fd39ddcdc323161ed58afb7f341d"
metafile = true

[[files]]
file = "mods/toil-and-trouble.pw.toml"
hash = "68e44081abd7af612892d61f762169767c5b617646e14058198a157bd209b4ef"
metafile = true

[[files]]
file = "mods/trailier-tales.pw.toml"
hash = "15fb3dfb0d8d55b3570825bed2eccebb1fe40bc6f751042c4c5dfaaba4e3f71e"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "90df8d95fcd836373dd1b26dd8f3fbc6ca8ac55f797e09562796aa0aeb0576c0"
metafile = true

[[files]]
file = "mods/wilder-wild.pw.toml"
hash = "6a28f1928252b131b3b1a78e938424dbb72c403d9a0d44e819c2998ee8ac34e7"
metafile = true

[[files]]
file = "mods/x-bar-theory.pw.toml"
hash = "9cf1b88fb7bec0cde48a50143d0bb8cd5e54fdd03e314c054fe2f182eaf14c57"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f82809b1d8eaab731b217b01589ab13e1374c4d422f18640ba3262b55f3b4cfa"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/yyzsbackpack-fabric-21.9.6-render-state-crash-patch.jar"
hash = "803946c6722eec90ea5b588d5c8f8e56ea38ef7862bdef1ff4eecdb990589085"
