name = "devOS Season Potluck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0837a03112fe7eae1ba7efe6184cae7b4f1868e2d96c53bc846b90aa50e04857"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21.9"]
