name = "devOS Season Potluck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e675541cba7ee14447b2490641559c2085e6b82b1b399c4a6ae802603261c3a"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21.9"]
