name = "devOS Season Potluck"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09418071f93e964c3199ed8bbaaa12d32828281bb4163cbd020a2ee744aeede2"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21.9"]
